name: Build & Test (C++20 + GTest)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: C++20 Build & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build git
          sudo apt-get install -y libgtest-dev
          cd /usr/src/gtest && sudo cmake . && sudo make && sudo cp lib/*.a /usr/lib

      - name: Configure Build
        run: |
          cmake -B build -S . -G "Unix Makefiles" -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: cmake --build build --parallel

      - name: Run Unit Tests
        run: |
          cd build
          ctest --output-on-failure
